---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-db-deployment
  labels:
    app: db-app
    username: ckk3478
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-app
      username: ckk3478
      env: test
  template:
    metadata:
      labels:
        app: db-app
        username: ckk3478
        env: test
    spec:
      containers:
        - name: db-app
          imagePullPolicy: Always
          image: casskk/app-rd:${TAG}
          command: ["redis-server"]
          volumeMounts:
          - name: app-db-pvc
            mountPath: "/data"
          ports:
          - name: http
            containerPort: 6379
      volumes:
      - name: app-db-pvc
        persistentVolumeClaim:
          claimName: app-db-pvc