---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: NAME8
  labels:
    app: NAME6
    username: ckk3478
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi