---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-db-pvc
  labels:
    app: db-app
    username: ckk3478
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi