---
apiVersion: v1
kind: Service
metadata:
  name: NAME9
  labels:
    app: NAME6
    username: ckk3478
    env: test
spec:
  type: ClusterIP
  selector:
    app: NAME6
  ports:
  - name: NAME7
    port: 6379
    targetPort: 6379