---
apiVersion: v1
kind: Service
metadata:
  name: app-db-service
  labels:
    app: db-app
    username: ckk3478
    env: test
spec:
  type: ClusterIP
  selector:
    app: db-app
  ports:
  - name: db-app
    port: 6379
    targetPort: 6379