FROM python:3.9

ADD requirements.txt /requirements.txt

RUN pip install -r requirements.txt

RUN pip install hotqueue

RUN pip install redis

RUN pip install matplotlib=3.3.4

COPY ./source/worker.py /app/

WORKDIR /app

CMD ["python", "/app/worker.py"]