FROM python:3.9

ADD requirements.txt /requirements.txt

RUN pip install -r requirements.txt

RUN pip install hotqueue

RUN pip install redis

RUN mkdir -p /app

COPY ./source/api.py /app/

WORKDIR /app

CMD ["python", "/app/api.py"]