---
version: "3"

services:
    casskk-api:
        image: casskk/app-api:${VER}
        container_name: casskk-api
        environment:
            - REDIS_IP= casskk-rd
        ports:
            - 5015:5000
    casskk-rd:
        image: casskk/app-rd:${VER}
        container_name: casskk-rd
        ports:
            - 6395:6379
        user: "869425:816966"
        volumes:
            - ../config/:/config/
    casskk-worker:
        image: casskk/app-worker:${VER}
        container_name: casskk-worker
        environment:
            - REDIS_IP=casskk-db