---
version: "3"

services:
    api:
        image: casskk/IMAGE_API_NAME
        volumes:
            - ./test:/data
        user: "827385:815499"
        command: api.py /data/animals.json
    redis:
        image: redis:latest
        container_name: casskk-redis
        ports:
            - 6395:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: ["redis-server", "/redis.conf"]
     work:
        image: casskk/IMAGE_WORK_NAME
        volumes:
            - ./test:/data
        user: "827385:815499"
        command: worker.py /data/animals.json
     web:
        build: .
        container_name: casskk-web
        ports:
           - 5015:5000
        volumes:
           - ./data/data_file.json:/datafile.json