---
apiVersion: v1
kind: Service
metadata:
  name: NAME4
  labels:
    app: NAME2
    username: ckk3478
    env: test
spec:
  type: ClusterIP
  selector:
    app: name2
  ports:
  - name: name3
  port: 5000
  targetPort: 5000