---
apiVersion: v1
kind: Service
metadata:
  name: app-api-service
  labels:
    app: api-app
    username: ckk3478
    env: test
spec:
  type: ClusterIP
  selector:
    app: api-app
  ports:
  - name: api-port
    port: 5000
    targetPort: 5000