---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api-deployment
  labels:
    app: api-app
    username: ckk3478
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
      username: ckk3478
      env: test
  template:
    metadata:
      labels:
        app: api-app
        username: ckk3478
        env: test
    spec:
      containers:
        - name: api-app
          imagePullPolicy: Always
          image: casskk/app-api:${TAG}
          command: ['python', 'api.py']
          env:
          - name: REDIS_IP
            value: 10.98.221.351
          ports:
          - name: http
            containerPort: 5000    