---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-worker-development
  labels:
    app: worker-app
    username: ckk3478
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
      username: ckk3478
      env: test
  template:
    metadata:
      labels:
        app: worker-app
        username: ckk3478
        env: test
    spec:
      containers:
        - name: worker-app
          imagePullPolicy: Always
          image: casskk/app-worker:${TAG}
          command: ['python', 'worker.py']
          env:
          - name: REDIS_IP
            value: 10.98.221.351
          - name: WORKER_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
          - name: http
            containerPort: 6379