---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: NAME11
  labels:
    app: NAME12
    username: ckk3478
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: NAME12
      username: ckk3478
      env: test
  template:
    metadata:
      labels:
        app: NAME12
        username: ckk3478
        env: test
    spec:
      containers:
        - name: NAME13
          imagePullPolicy: Always
          image: casskk/FLASK_API_IMAGE_NAME => maybe different??????????
          command: ['python', 'worker.py']
          env:
          - name: WORKER_GREETING
            value: "Hello from worker.py"
          - name: WORKER_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
          - name: http
            containerPort: 6379